### ISSUE TITLE
unable to download blueprint

### ISSUE THREAD

**Issue by CelticKernowGaming** [GoodAI/space-engineers-ai-spaceship-generator#3] opened 2022-10-27 21:48 UTC
Cant download any blueprints

high (application-breaking) 

**Describe the issue**
I am able to use your aplicxation however everysincel time i try to download the blueprints I am left with the Your selected spaceship will be downloaded shortly.Your selected spaceship will be downloaded shortly. text

I have left it for over 1 hour on a first genuration with a total number of blocks only 5629 

**To Reproduce**
followed all the steps in your information for the genurator and also folled step by step on the live stream but have the same result

**Expected behavior**
watch the stream it should have downloded the ships 

**Desktop (please complete the following information):**
 - OS: windows 10 latest version
 - Browser: Chrome
 - .exe file name: [Spaceship.Generator.v1.0.1.exe]

**Additional context**

**Comment by Toobyular** [comment] 2022-10-28 02:33
I have this same issue.

My pc has a 12900k and 32gb of 5600mhz ddr5 ram and I have left it trying to download a BP for about 2 hours without success.

**Comment by gallorob** [comment] 2022-10-28 03:08
It should not take _that_ long indeed, this is strange, If possible, can you attach the log file that is generated by the application (currently the executable creates the log in a temporary folder, this will be fixed with the next release, but if you run it from source it will be created in the same directory)? I could then take a look and see what the issue may be.

As an additional piece of information, does the spinner on the top right remain visible for the entire time or does it disappear after a while?

**Comment by CelticKernowGaming** [comment] 2022-10-28 13:37
Just seen your message I have tryed again to see if i could recreate the issue again i have been waiting for over an hour. with regards to the spinner. yes it is still spinning. the model displayed is still interactive and can move it about. all other buttons are grayed out. 
I have attached this log ID = 226558694618542469228478071646456287396.
Also I have attached a second one with the same issue i reported yesterday 
ID = 178252536867229767763732540128706032818.
on both occasions i get this message Your selected spaceship will be downloaded shortly.
[log_20221028130838.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9888842/log_20221028130838.log)
[log_20221027221857.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9888843/log_20221027221857.log)

**Comment by gallorob** [comment] 2022-10-30 00:35
@CelticKernowGaming thank you so much! Judging by the logs, it seems like the actual download process does not start... I have also read of few other people affected by this issue, but it's unclear what's the cause. I will look more into this, and will push an update with some more debugging messages so I can pinpoint (hopefully) the problem tomorrow-ish.

Are you able to run the application from source code instead of executable? That might help solving this issue faster as you wouldn't have to wait for each release.

**Comment by Turtlehunter2** [comment] 2022-10-30 03:54
I'm having the same issue, I try to download a ship and it just sits and says my download will start shortly.

**Comment by gallorob** [comment] 2022-10-31 00:08
@CelticKernowGaming I have added a few debugging messages in https://github.com/arayabrain/space-engineers-ai-spaceship-generator/commit/41f33b990b1a901b71d938637466c8bfbe73bca2, here's an example output:

```
[2022-10-31 08:58:25,089] Your selected spaceship will be downloaded shortly.
[2022-10-31 08:58:25,089] [pcgsepy.guis.main_webapp.webapp.write_archive] Started function, writing zip file...
...
[2022-10-31 08:58:30,317] [pcgsepy.guis.main_webapp.webapp.write_archive] Loaded elite solution elite={...}.
[2022-10-31 08:58:30,616] [pcgsepy.guis.main_webapp.webapp.write_archive] Copied threadsafe elite solution, starting hullbuilding...
[2022-10-31 08:58:30,649] [pcgsepy.guis.main_webapp.webapp.write_archive] Added external hull, unlocking semaphore...
[2022-10-31 08:58:30,664] [pcgsepy.guis.main_webapp.webapp.write_archive] download_semaphore.is_locked=False
...
[2022-10-31 08:59:33,343] [pcgsepy.guis.main_webapp.webapp.write_archive] tmp.string='{...}'; tmp.content={N}x Structure with {N} blocks; tmp.base_color={'x': {...}, 'y': {...}, 'z': {...}}
...
[2022-10-31 08:59:33,414] [pcgsepy.guis.main_webapp.webapp.write_archive] Created game blueprint, saving spaceship string representation...
[2022-10-31 08:59:33,415] [pcgsepy.guis.main_webapp.webapp.write_archive] Zip file completed and ready to be downloaded.
```

This obviously does not fix the problem, but it is a good way to understand where the issue is. Let me know if you can run it from source or if you need the executable.

@Turtlehunter2 @Toobyular could you guys also try and run from source? What browser are you using?

**Comment by gallorob** [comment] 2022-10-31 00:54
@CelticKernowGaming @Turtlehunter2 @Toobyular I published the executable with the [above ](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/3#issuecomment-1296387813)changes at https://github.com/GoodAI/space-engineers-ai-spaceship-generator/releases/tag/internal-testing, please download it and try downloading a spaceship--if it takes again too long, terminate the application and attach the log file (generated in the same directory where you placed the executable) so I can take a look.

If you want to make sure you don't terminate the application too early, you can launch the executable with the debug flag (`AI.Spaceship.Generator.v1.0.0.internal.exe --debug`), which will print on your console _all_ debug messages. Keep an eye out for the ones I copied [above](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/3#issuecomment-1296387813).

**Comment by Turtlehunter2** [comment] 2022-10-31 19:09
@gallorob the internal testing version didn't fix it, and i'm not tech savvy enough to find and launch it from the source code. 
[log_20221031134600.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9904111/log_20221031134600.log)
here's my log, the final line said the semaphore was locked before stopping for 10 minutes, I'm wondering if that's what's causing the issue

**Comment by CelticKernowGaming** [comment] 2022-10-31 20:05
@gallorob 
I have run the executable file twice with the same issue. one I tried to download the first ship I clicked on and the other was with 10 iterations. gave both of them over an hour to download but with no success. 
Unfortunately I am unsure as to how to lunch the programe via sorce code Is there a program to do this ?

I have attached both the logs. 
[log_20221031191637.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9904695/log_20221031191637.log)
[log_20221031175011.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9904696/log_20221031175011.log)

**Comment by Toobyular** [comment] 2022-10-31 20:09
Here you go

I was wondering if it was browser related. I am on the latest Firefox. Here is that log
[log_20221031130407.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9904723/log_20221031130407.log)

**Comment by Toobyular** [comment] 2022-10-31 20:12
And here I repeated the same steps but with my default browser being Microsoft Edge

(steps are open app > no > select the smallest ship > click download
[log_20221031130941.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9904740/log_20221031130941.log)

**Comment by gallorob** [comment] 2022-11-01 00:28
Hi everyone, thank you for testing the changes so quickly! This internal release was not supposed to fix the issue, but to help me understand the root problem, as I'm unable to reproduce it and investigate on my own.

 I've looked through the log files, interestingly enough the zip file gets created (I could see `[pcgsepy.guis.main_webapp.webapp.write_archive] Started function, writing zip file...` in all log files), but then the entire thread hangs--which is weird since the first thing it creates is the thumbnail from the spaceship preview plot.

Also thank you for checking on different browsers as well @Toobyular, that really helps. 

I've updated the internal release executable (https://github.com/GoodAI/space-engineers-ai-spaceship-generator/releases/tag/internal-testing), so please download it again and try download a spaceship again. It will fail, but the log file now will include a line-by-line debugging message, so I can see the exact point where this issue is located.

In order not to waste too much of your time, follow @Toobyular steps:
> (steps are open app > no > select the smallest ship > click download

Finally, a reminder to make sure you tick the "Unblock" checkbox in the executable properties, and try also running in Administrator mode.

I will be out of the country for the next few days, so I won't be able to publish new fixes, but I will read the comments here and the log files.

**Comment by Toobyular** [comment] 2022-11-01 01:37
Without running as admin > 
[log_20221031182119.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9905978/log_20221031182119.log)

Running as admin > 
[log_20221031183313.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9905997/log_20221031183313.log)

**Comment by gallorob** [comment] 2022-11-01 02:20
@Toobyular amazing, thank you! It seems that the culprit is the `to_image` method used to convert the spaceship preview to a static image. Looking around, the issue seems to be pretty common (see [here](https://github.com/plotly/Kaleido/issues/98), [here](https://stackoverflow.com/questions/70997997/not-able-to-save-plotly-plots-using-to-image-or-write-image) or [here](https://stackoverflow.com/questions/70997997/not-able-to-save-plotly-plots-using-to-image-or-write-image)) and also pretty unclear what actually helps to fix it, so I will create a bunch of different executables for you all to try out--hopefully just one version is needed in the end.

The light at the end of the tunnel is near 😄

**Comment by Toobyular** [comment] 2022-11-10 19:19
Any updates on this?

**Comment by CelticKernowGaming** [comment] 2022-11-11 00:03
@gallorob I have attached my log doc. followed all the steps you advised and was in admin mode whilst running the program 
[log_20221110225012.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9985399/log_20221110225012.log)
I used the exe from your last post 10 days ago.

**Comment by gallorob** [comment] 2022-11-11 10:02
@CelticKernowGaming thank you!

@CelticKernowGaming @Turtlehunter2 @Toobyular I have updated the `internal-testing` [release](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/releases/tag/internal-testing) with three versions of the application (vA, vB, and vC). Since I could not replicate this issue, each version has a different possible fix to this bug. Please test them as before and let me know which version works (hopefully the same for everyone involved).

Follow the same instructions as described in the reply above:
> steps are open app > no > select the smallest ship > click download

And again, make sure you tick the "Unblock" checkbox in the executable properties, and try also running in Administrator mode.

Sorry for the late update, as I said I was out of the country for a few days and then got sick, but now I can resume work 😃

**Comment by CelticKernowGaming** [comment] 2022-11-11 13:27
@gallorob 
Just tryed all three of the exe. 
two failed 
[log_20221111130215.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9990497/log_20221111130215.log)
log_20221111130215 used version A
[log_20221111131047.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9990502/log_20221111131047.log)
log_20221111131047 used version B
both had the same stopping Point Updated thumbnail camera...

But version C worked for me.
I have not tested it in game yet as i am about to go work but option C on the steps above worked I will need to just do more indepth testing later today when i get back home to make sure its all good but I at least got the downloaded file
the log is here
[log_20221111131843.log](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9990506/log_20221111131843.log)

**Comment by gallorob** [comment] 2022-11-11 13:34
@CelticKernowGaming I'm so relieved to hear that! Hopefully vC works for the other guys as well and we can push it as next release 🤞

**Comment by Toobyular** [comment] 2022-11-11 18:25
Looks like version C worked for me as well, with the first two failing. I did not have to run as admin. Both failed logs ended with " [2022-11-11 10:18:55,810] [pcgsepy.guis.main_webapp.webapp.write_archive] Updated thumbnail camera... "

Also, I don't know what this unblock checkbox is as I've never found it, lol

**Comment by gallorob** [comment] 2022-11-11 19:29
@Toobyular great! Let's wait a bit and see if vC works for @Turtlehunter2 as well.

In the meantime, while we prepare the next release, you can use the vC executable to run the application to either play around in user mode or participate in the user study (and if you run into any more issues, let me know).

PS: The "unblock" option is in the properties tab (right click on the executable -> Properties -> General) at the bottom:
![immagine](https://user-images.githubusercontent.com/32876132/201415874-524e12cb-cec6-42b8-90a4-3877c195cbdb.png)
When you download it from Github it usually looks like that.

**Comment by Toobyular** [comment] 2022-11-12 01:30
Ahhh, you must be on a different OS version I'm guessing. Mine looks like this

![image](https://user-images.githubusercontent.com/64458475/201450290-f80f9cf9-efd9-4237-801f-7fc9ae3cfd80.png)

**Comment by Turtlehunter2** [comment] 2022-11-12 04:03
Version C works, it took a while but I got the blueprint and it loaded in fine, didn't need to do anything fancy to make it work

**Comment by gallorob** [comment] 2022-11-16 20:30
Fix has been implemented in the [latest release](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/releases/tag/v1.0.3), closing this issue.

**Closed by gallorob** 2022-11-16 20:30 UTC
